using Autodesk.Revit.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BsddRevitPlugin.Logic.Model
{
    public static class ArrayHolder
    {
        public static readonly string[] RevitGeoCategoriesArray =
        {
            //"Abutment Foundation Tags",
            //"Abutment Pile Tags",
            //"Abutment Tags",
            //"Abutment Wall Tags",
            "Abutments",
            "Air Terminals",
            //"Alignment Station Label Sets",
            //"Alignment Station Labels",
            //"Alignment Tags",
            //"Alignments",
            //"Analytical Member Tags",
            //"Analytical Members",
            //"Analytical Opening Tags",
            //"Analytical Openings",
            //"Analytical Panel Tags",
            //"Analytical Panels",
            //"Anchor Tags",
            //"Approach Slab Tags",
            //"Area Based Load Tags",
            //"Area Polylines",
            //"Area Tags",
            "Areas",
            "Assemblies",
            //"Audio Visual Device Tags",
            "Audio Visual Devices",
            //"Bearing Tags",
            "Bearings",
            //"Bolt Tags",
            //"Bridge Arch Tags",
            //"Bridge Cable Tags",
            "Bridge Cables",
            //"Bridge Cross Bracing Tags",
            //"Bridge Deck Tags",
            "Bridge Decks",
            //"Bridge Diaphragm Tags",
            "Bridge Framing",
            //"Bridge Girder Tags",
            //"Bridge Truss Tags",
            "Cable Tray Fittings",
            "Cable Trays",
            //"Callouts",
            "Casework",
            //"Casework Tags",
            //"Ceiling Tags",
            "Ceilings",
            //"Color Fill Legends",
            //"Column Tags",
            "Columns",
            "Communication Devices",
            "Conduit Fittings",
            "Conduits",
            //"Constraints",
            //"Contour Labels",
            //"Curtain Panel Tags",
            "Curtain Panels",
            "Curtain Systems",
            //"Curtain Wall Mullion Tags",
            "Curtain Wall Mullions",
            "Data Devices",
            //"Demolished",
            //"Detail Items",
            //"Dimensions",
            //"Door Tags",
            "Doors",
            "Duct Accessories",
            "Duct Fittings",
            "Duct Insulations",
            "Duct Linings",
            "Duct Placeholders",
            "Ducts",
            "Electrical Equipment",
            //"Electrical Equipment Tags",
            //"Electrical Fixture Tags",
            "Electrical Fixtures",
            //"Elevations",
            "Entourage",
            //"Entourage Tags",
            //"Existing",
            //"Expansion Joint Tags",
            "Expansion Joints",
            //"Fascia Tags",
            //"Filled region",
            "Fire Alarm Devices",
            "Fire Protection",
            "Flex Ducts",
            "Flex Pipes",
            "Floors",
            "Food Service Equipment",
            //"Food Service Equipment Tags",
            "Furniture",
            "Furniture Systems",
            //"Generic Annotations",
            //"Generic Model Tags",
            "Generic Models",
            //"Grids",
            //"Gutter Tags",
            //"Handrail Tags",
            "Hardscape",
            //"Hardscape Tags",
            //"Hole Tags",
            "HVAC Zones",
            "Imports in Families",
            //"Levels",
            "Lighting Devices",
            //"Lighting Fixture Tags",
            "Lighting Fixtures",
            //"Lines",
            "Mass",
            "Massing",
            //"Mechanical Control Device Tags",
            "Mechanical Control Devices",
            "Mechanical Equipment",
            //"Mechanical Equipment Set Boundary Lines",
            //"Mechanical Equipment Set Tags",
            //"Mechanical Equipment Tags",
            "Medical Equipment",
            //"Medical Equipment Tags",
            "MEP Fabrication Containment",
            "MEP Fabrication Ductwork",
            "MEP Fabrication Hangers",
            "MEP Fabrication Pipework",
            //"Model Group Tags",
            //"Multi-Category Tags",
            //"New",
            "Nurse Call Devices",
            //"Pad Tags",
            //"Panel Schedule Graphics",
            "Parking",
            "Parts",
            //"Path of Travel Tags",
            //"Pier Cap Tags",
            //"Pier Column Tags",
            //"Pier Foundation Tags",
            //"Pier Pile Tags",
            //"Pier Tags",
            //"Pier Tower Tags",
            //"Pier Wall Tags",
            "Piers",
            "Pipe Accessories",
            "Pipe Fittings",
            "Pipe Insulations",
            "Pipe Placeholders",
            "Pipes",
            //"Plan Region",
            "Planting",
            //"Planting Tags",
            //"Plate Tags",
            "Plumbing Equipment",
            //"Plumbing Equipment Tags",
            //"Plumbing Fixture Tags",
            "Plumbing Fixtures",
            //"Point Clouds",
            //"Profile Tags",
            //"Property Line Segment Tags",
            //"Property Tags",
            //"Railing Tags",
            "Railings",
            //"Ramp Tags",
            "Ramps",
            //"Raster Images",
            //"Reference Planes",
            //"Road Tags",
            "Roads",
            //"Roof Soffit Tags",
            //"Roof Tags",
            "Roofs",
            //"Room Polylines",
            //"Room Tags",
            "Rooms",
            "Ruled Curtain System",
            //"RVT Link Tags",
            //"Schedule Graphics",
            //"Scope Boxes",
            //"Sections",
            "Security Devices",
            "Shaft Openings",
            //"Shear Stud Tags",
            "Signage",
            //"Signage Tags",
            "Site",
            //"Site Tags",
            //"Slab Edge Tags",
            "Spaces",
            "Specialty Equipment",
            //"Specialty Equipment Tags",
            //"Spot Coordinates",
            //"Spot Elevations",
            //"Spot Slopes",
            "Sprinklers",
            //"Stair Landing Tags",
            //"Stair Paths",
            //"Stair Run Tags",
            //"Stair Support Tags",
            //"Stair Tags",
            //"Stair Tread/Riser Numbers",
            "Stairs",
            "Structural Area Reinforcement",
            "Structural Beam Systems",
            //"Structural Column Tags",
            "Structural Columns",
            "Structural Connections",
            "Structural Fabric Areas",
            //"Structural Fabric Areas Boundary",
            "Structural Fabric Reinforcement",
            //"Structural Fabric Reinforcement Boundary",
            "Structural Fabric Reinforcement Fabric Wire",
            //"Structural Foundation Tags",
            "Structural Foundations",
            "Structural Framing",
            //"Structural Framing Tags",
            "Structural Path Reinforcement",
            "Structural Rebar",
            "Structural Rebar Couplers",
            //"Structural Stiffener Tags",
            "Structural Stiffeners",
            //"Structural Tendon Tags",
            "Structural Tendons",
            //"Structural Truss Tags",
            "Structural Trusses",
            "Telephone Devices",
            "Temporary",
            //"Temporary Structure Tags",
            "Temporary Structures",
            //"Text Notes",
            //"Title Blocks",
            //"Top Rail Tags",
            "Topography",
            "Vertical Circulation",
            //"Vertical Circulation Tags",
            //"Vibration Damper Tags",
            //"Vibration Isolator Tags",
            //"Vibration Management",
            //"Vibration Management Tags",
            //"View Titles",
            //"Wall Sweep Tags",
            //"Wall Tags",
            "Walls",
            "Walls/Interior:1",
            "Walls/Exterior:2",
            "Walls/Foundation:3",
            "Walls/Retaining:4",
            //"Weld Tags",
            //"Window Tags",
            "Windows",
            "Wires"
        };
    }
}
